name: Staging

on:
  push:
    branches:
      - develop
  pull_request:
    branches: [ develop ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, sqlite

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Cache Composer deps
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Generate key & set perms
        run: |
          php artisan key:generate
          chmod -R 777 storage bootstrap/cache

      - name: Create SQLite database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Cache NPM deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install & build assets
        run: |
          npm ci
          npm run production

      - name: Run PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit

      - name: Run Jest
        run: npm test


  build:
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - name: Install NPM dependencies
        run: npm install
      - name: Compile assets for production
        run: npm run production

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Commit built assets
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Do Something with env files
        env:
          DOT_ENV: ${{ secrets.DOT_ENV_STAGING }}
        run: |
          echo $DOT_ENV > .env
      - name: Deployment
        uses: appleboy/ssh-action@master
        env:
          DOT_ENV: ${{ secrets.DOT_ENV_STAGING }}
          BASE_PATH: ${{ secrets.PATH_STAGING }}
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          envs: DOT_ENV,BASE_PATH
          script: |
            cd ${BASE_PATH}
            bash server_deploy.sh

